% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Tugas Kelompok Analisis Regresi},
  pdfauthor={Kelompok 9},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Tugas Kelompok Analisis Regresi}
\author{Kelompok 9}
\date{2024-02-10}

\begin{document}
\maketitle

Anggota kelompok 9:\\
Deden Ahmad Rabani (G1401221016)\\
Nabil Bintang Prayoga (G1401221017)\\
Fathiyya Mufida (G1401220931)

\hypertarget{membaca-data-csv}{%
\section{\texorpdfstring{ MEMBACA DATA
CSV}{ MEMBACA DATA CSV}}\label{membaca-data-csv}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/nbint/Downloads/2019.csv"}\NormalTok{, }\AttributeTok{sep=}\StringTok{","}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Overall.rank Country.or.region Score GDP.per.capita Social.support
## 1            1           Finland 7.769          1.340          1.587
## 2            2           Denmark 7.600          1.383          1.573
## 3            3            Norway 7.554          1.488          1.582
## 4            4           Iceland 7.494          1.380          1.624
## 5            5       Netherlands 7.488          1.396          1.522
## 6            6       Switzerland 7.480          1.452          1.526
##   Healthy.life.expectancy Freedom.to.make.life.choices Generosity
## 1                   0.986                        0.596      0.153
## 2                   0.996                        0.592      0.252
## 3                   1.028                        0.603      0.271
## 4                   1.026                        0.591      0.354
## 5                   0.999                        0.557      0.322
## 6                   1.052                        0.572      0.263
##   Perceptions.of.corruption
## 1                     0.393
## 2                     0.410
## 3                     0.341
## 4                     0.118
## 5                     0.298
## 6                     0.343
\end{verbatim}

\hypertarget{pendefinisian-variabel}{%
\subsection{\texorpdfstring{ Pendefinisian
Variabel}{ Pendefinisian Variabel}}\label{pendefinisian-variabel}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Country}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Country.or.region}
\NormalTok{Y}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Score}
\NormalTok{X1}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{GDP.per.capita}
\NormalTok{X2}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Social.support}
\NormalTok{X3}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Healthy.life.expectancy}
\NormalTok{X4}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Freedom.to.make.life.choices}
\NormalTok{X5}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Generosity}
\NormalTok{X6}\OtherTok{\textless{}{-}}\NormalTok{data}\SpecialCharTok{$}\NormalTok{Perceptions.of.corruption}
\end{Highlighting}
\end{Shaded}

\hypertarget{data-dengan-nama-variabel-baru}{%
\subsection{\texorpdfstring{ Data dengan Nama Variabel
Baru}{ Data dengan Nama Variabel Baru}}\label{data-dengan-nama-variabel-baru}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OtherTok{\textless{}{-}}\FunctionTok{data.frame}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(Y,X1,X2,X3,X4,X5,X6))}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Y    X1    X2    X3    X4    X5    X6
## 1 7.769 1.340 1.587 0.986 0.596 0.153 0.393
## 2 7.600 1.383 1.573 0.996 0.592 0.252 0.410
## 3 7.554 1.488 1.582 1.028 0.603 0.271 0.341
## 4 7.494 1.380 1.624 1.026 0.591 0.354 0.118
## 5 7.488 1.396 1.522 0.999 0.557 0.322 0.298
## 6 7.480 1.452 1.526 1.052 0.572 0.263 0.343
\end{verbatim}

\hypertarget{hitung-baris-dan-kolom}{%
\subsection{\texorpdfstring{ Hitung Baris dan
Kolom}{ Hitung Baris dan Kolom}}\label{hitung-baris-dan-kolom}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(n}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 156
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(p}\OtherTok{\textless{}{-}}\FunctionTok{ncol}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7
\end{verbatim}

Pada analisis regresi linier sederhana ini, data yang digunakan diambil
dari situs kaggle.com/dataset berupa penelitian terkait tingkat
kebahagiaan di setiap negara atau wilayah pada tahun 2019. Skor tersebut
didasarkan pada jawaban dari pertanyaan yang diajukan dalam jajak
pendapat yang dikenal sebagai tangga cantril, meminta responden untuk
memikirkan prioritas dari skala 0 sampai 10. Skor berasal dari sampel
yang representatif secara nasional dari 156 negara atau wilayah.

Variabel Y pada data ini adalah skor tingkat kebahagiaan di setiap
negara dan dari 6 variabel X yang tersedia, dipilih X1 yaitu GDP per
kapita sebagai variabel yang digunakan pada analisis ini. Berdasarkan
penelitian sebelumnya, peningkatan pendapatan dapat meningkatkan tingkat
kebahagiaan. Implikasi dari temuan ini adalah tingkat kebahagiaan dari
masyarakat suatu wilayah dapat didorong dengan peningkatan pendapatan,
karena pendapatan merupakan faktor penting untuk mendapatkan dan membuka
akses pangan, kesehatan, dan layanan umum, sehingga meningkatkan
kualitas kehidupan yang lebih baik yang berimplikasi kebahagiaan pun
meningkat (Fajar dan Eko, 2022). Oleh karenanya, kami ingin menganalisis
pengaruh GDP per kapita terhadap tingkat kebahagiaan di suatu negara
atau wilayah berdasarkan data yang sudah ada.

\hypertarget{eksplorasi-data}{%
\section{\texorpdfstring{ EKSPLORASI
DATA}{ EKSPLORASI DATA}}\label{eksplorasi-data}}

Scatter plot di bawah ini menggambarkan hubungan antara X1 (GDP per
kapita) dan Y (skor tingkat kebahagiaan) yang linier positif. Semakin
tinggi GDP per kapita, maka skor tingkat kebahagiaan juga semakin
tinggi.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(X1,Y)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Kelompok-9-Analisis-Regresi-Tugas-1_files/figure-latex/unnamed-chunk-5-1.pdf}

\hypertarget{rangkuman-statistik-variabel-y}{%
\subsection{\texorpdfstring{ Rangkuman Statistik Variabel
Y}{ Rangkuman Statistik Variabel Y}}\label{rangkuman-statistik-variabel-y}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(Y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.853   4.545   5.380   5.407   6.184   7.769
\end{verbatim}

\hypertarget{rangkuman-statistik-variabel-x1}{%
\subsection{\texorpdfstring{ Rangkuman Statistik Variabel
X1}{ Rangkuman Statistik Variabel X1}}\label{rangkuman-statistik-variabel-x1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(X1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.6028  0.9600  0.9051  1.2325  1.6840
\end{verbatim}

\hypertarget{analisis-data-dengan-fungsi-lm}{%
\section{\texorpdfstring{ ANALISIS DATA DENGAN FUNGSI
LM}{ ANALISIS DATA DENGAN FUNGSI LM}}\label{analisis-data-dengan-fungsi-lm}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(Y}\SpecialCharTok{\textasciitilde{}}\NormalTok{X1,data}\OtherTok{\textless{}{-}}\NormalTok{data)}
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X1, data = data <- data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.22044 -0.48361  0.00828  0.48433  1.47409 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   3.3993     0.1353   25.12   <2e-16 ***
## X1            2.2181     0.1369   16.20   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.679 on 154 degrees of freedom
## Multiple R-squared:  0.6303, Adjusted R-squared:  0.6278 
## F-statistic: 262.5 on 1 and 154 DF,  p-value: < 2.2e-16
\end{verbatim}

Dari hasil tersebut, diperoleh dugaan persamaan regresi sebagai berikut
\[\hat{y}=3.3993+2.2181{x}\] dengan b0 adalah 2.2181 dan b1 adalah
3.3993\\
Artinya jika nilai GDP per kapita di suatu negara atau wilayah meningkat
1 satuan maka dugaan skor tingkat kebahagiaan akan meningkat sebesar
2.2181 dan ketika GDP per kapita bernilai 0 maka skor tingkat
kebahagiaan di suatu negara atau wilayah adalah sebesar 3.3993

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(anova.model}\OtherTok{\textless{}{-}}\FunctionTok{anova}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Y
##            Df  Sum Sq Mean Sq F value    Pr(>F)    
## X1          1 121.040 121.040   262.5 < 2.2e-16 ***
## Residuals 154  71.011   0.461                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{ukuran-kebaikan-model}{%
\subsection{\texorpdfstring{ Ukuran Kebaikan
Model}{ Ukuran Kebaikan Model}}\label{ukuran-kebaikan-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(Koef\_det}\OtherTok{\textless{}{-}}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(anova.model}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Sum Sq}\StringTok{\textasciigrave{}}\NormalTok{[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(anova.model}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Sum Sq}\StringTok{\textasciigrave{}}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.63025
\end{verbatim}

Koefisien determinasi menunjukkan angka sebesar 0.63025 atau 63.025\%,
artinya bahwa variasi skor tingkat kebahagiaan mampu dijelaskan oleh
variasi GDP per kapita sebesar 63.025\%. Sisanya sebesar 36.975\%
variasi skor tingkat kebahagiaan dijelaskan oleh faktor atau variabel
lain di luar model.

\hypertarget{keragaman-dugaan-parameter}{%
\section{\texorpdfstring{ KERAGAMAN DUGAAN
PARAMETER}{ KERAGAMAN DUGAAN PARAMETER}}\label{keragaman-dugaan-parameter}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{,}\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{,}\AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.975488
\end{verbatim}

\hypertarget{dugaan-parameter-beta_0}{%
\subsection{\texorpdfstring{ Dugaan parameter
\(\beta_0\)}{ Dugaan parameter \textbackslash beta\_0}}\label{dugaan-parameter-beta_0}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(b0}\OtherTok{\textless{}{-}}\NormalTok{model}\SpecialCharTok{$}\NormalTok{coefficients[[}\DecValTok{1}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.399345
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(se\_b0}\OtherTok{\textless{}{-}}\FunctionTok{sqrt}\NormalTok{(anova.model}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Mean Sq}\StringTok{\textasciigrave{}}\NormalTok{[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{n}\SpecialCharTok{+}\FunctionTok{mean}\NormalTok{(X1)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{((X1}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(X1))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1353233
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(t\_b0 }\OtherTok{\textless{}{-}}\NormalTok{ b0}\SpecialCharTok{/}\NormalTok{se\_b0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 25.12018
\end{verbatim}

\hypertarget{hipotesis-uji-beta_0}{%
\subsubsection{\texorpdfstring{ Hipotesis Uji
\(\beta_0\)}{ Hipotesis Uji \textbackslash beta\_0}}\label{hipotesis-uji-beta_0}}

\(H_0:\beta_0=0\) (semua skor tingkat kebahagiaan dapat dijelaskan oleh
besarnya GDP per kapita)\\
\(H_0:\beta_0≠0\) (ada skor tingkat kebahagiaan yang tidak dapat
dijelaskan oleh besarnya GDP per kapita)\\
Karena t = 25.12 \textgreater{} \(t(0.05/2;156-2)\) = 1.975 maka tolak
\(H_0\), sehingga cukup bukti untuk menyatakan bahwa ada skor tingkat
kebahagiaan yang tidak dapat dijelaskan oleh besarnya GDP per kapita
pada taraf nyata 5\%.

\hypertarget{dugaan-parameter-beta_1}{%
\subsection{\texorpdfstring{ Dugaan Parameter
\(\beta_1\)}{ Dugaan Parameter \textbackslash beta\_1}}\label{dugaan-parameter-beta_1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(b1}\OtherTok{\textless{}{-}}\NormalTok{model}\SpecialCharTok{$}\NormalTok{coefficients[[}\DecValTok{2}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.218148
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(se\_b1}\OtherTok{\textless{}{-}}\FunctionTok{sqrt}\NormalTok{(anova.model}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Mean Sq}\StringTok{\textasciigrave{}}\NormalTok{[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{((X1}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(X1))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1369077
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(t\_b1}\OtherTok{\textless{}{-}}\NormalTok{b1}\SpecialCharTok{/}\NormalTok{se\_b1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.20178
\end{verbatim}

\hypertarget{hipotesis-uji-beta_1}{%
\subsubsection{\texorpdfstring{ Hipotesis Uji
\(\beta_1\)}{ Hipotesis Uji \textbackslash beta\_1}}\label{hipotesis-uji-beta_1}}

\(H_0:\beta_1=0\) (tidak ada hubungan linier antara GDP per kapita
dengan skor tingkat kebahagiaan)\\
\(H_0:\beta_1≠0\) (ada hubungan linier antara GDP per kapita dengan skor
tingkat kebahagiaan)\\
Karena t = 16.20 \textgreater{} \(t(0.05/2;156-2)\) = 1.975 maka tolak
\(H_0\) yang menunjukkan adanya hubungan linier antara GDP per kapita
dengan skor tingkat kebahagiaan. Sehingga cukup bukti untuk menyatakan
bahwa nilai GDP per kapita memngaruhi besarnya skor tingkat kebahagiaan
suatu negata atau wilayah pada taraf nyata 5\%.

\hypertarget{selang-kepercayaan-parameter}{%
\section{\texorpdfstring{ SELANG KEPERCAYAAN
PARAMETER}{ SELANG KEPERCAYAAN PARAMETER}}\label{selang-kepercayaan-parameter}}

\hypertarget{selang-kepercayaan-beta_0}{%
\subsection{\texorpdfstring{ Selang kepercayaan
\(\beta_0\)}{ Selang kepercayaan \textbackslash beta\_0}}\label{selang-kepercayaan-beta_0}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(sk.b0}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(b0}\SpecialCharTok{{-}}\FunctionTok{abs}\NormalTok{(}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}\SpecialCharTok{*}\NormalTok{se\_b0, b0 }\SpecialCharTok{+} \FunctionTok{abs}\NormalTok{(}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}\SpecialCharTok{*}\NormalTok{se\_b0))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.132016 3.666675
\end{verbatim}

Jadi, pada taraf nyata 5\%, diyakini bahwa dugaan parameter \(\beta_0\)
berada pada selang 3.123016 sampai 3.666675

\hypertarget{selang-kepercayaan-beta_1}{%
\subsection{\texorpdfstring{ Selang kepercayaan
\(\beta_1\)}{ Selang kepercayaan \textbackslash beta\_1}}\label{selang-kepercayaan-beta_1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(sk.b1}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(b1}\SpecialCharTok{{-}}\FunctionTok{abs}\NormalTok{(}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}\SpecialCharTok{*}\NormalTok{se\_b1, b1 }\SpecialCharTok{+} \FunctionTok{abs}\NormalTok{(}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\AttributeTok{df=}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}\SpecialCharTok{*}\NormalTok{se\_b1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.947689 2.488607
\end{verbatim}

Jadi, pada taraf nyata 5\%, diyakini bahwa dugaan parameter \(\beta_1\)
berada pada selang 1.947689 sampai 2.488607

\hypertarget{selang-kepercayaan-rataan-nilai-harapan-amatan}{%
\section{\texorpdfstring{ SELANG KEPERCAYAAN RATAAN (NILAI HARAPAN)
AMATAN}{ SELANG KEPERCAYAAN RATAAN (NILAI HARAPAN) AMATAN}}\label{selang-kepercayaan-rataan-nilai-harapan-amatan}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{amatan.diduga }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{X1=}\FloatTok{1.245}\NormalTok{)}
\FunctionTok{predict}\NormalTok{(model, amatan.diduga, }\AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 6.160939 6.019575 6.302304
\end{verbatim}

Misal ingin menduga nilai rataan (harapan) amatan ketika nilai GDP per
kapita negara tertentu adalah 1.245, maka diperoleh dugaan rataan skor
tingkat kebahagiaan sebesar 6.160939\\
Selain itu diindikasikan juga bahwa dalam taraf kepercayaan 95\%,
diyakini bahwa nilai dugaan rataan skor tingkat kebahagiaan ketika nilai
GDP per kapita adalah 1.245 berada dalam selang 6.019575 hingga 6.302304

\hypertarget{selang-kepercayaan-individu-amatan}{%
\section{\texorpdfstring{ SELANG KEPERCAYAAN INDIVIDU
AMATAN}{ SELANG KEPERCAYAAN INDIVIDU AMATAN}}\label{selang-kepercayaan-individu-amatan}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(model, amatan.diduga, }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 6.160939 4.812057 7.509822
\end{verbatim}

Misal ingin menduga nilai individu amatan ketika nilai GDP per kapita
negara tertentu adalah 1.245, maka diperoleh dugaan skor tingkat
kebahagiaan sebesar 6.160939\\
Selain itu diindikasikan juga bahwa dalam taraf kepercayaan 95\%,
diyakini bahwa nilai amatan individu skor tingkat kebahagiaan ketika
nilai GDP per kapita adalah 1.245 berada dalam selang 4.812057 hingga
7.509822

\end{document}
